export const API_BASEURL= "https://0r6lvr6q-3000.inc1.devtunnels.ms/api/v1";


export const tempBody={
    "general questions and additional supplements": {
      "Have Heartburn?": "Yes",
      "Can't tolerate Hydrozyme?": "Yes",
      "Histamine issues?": "Yes",
      "No gallbladder?": "Yes",
      "Constipated?": "Yes",
      "Have you undertaken a round of gut healing recently?": "No",
      "Want a multi-vitamin?": "No",
      "Have cancer that is active?": "No",
      "Emotional stress?": "No",
      "Have you been working on a ketogenic diet for at least two months?": "No",
      "Do you have hypoglycemic symptoms such as being 'hangry' between meals, lightheaded/dizzy, energized after eating?": "No",
      "Hypothyroid symptoms?\n(fatigue, weight gain/hard to lose weight, sensitive to cold, sluggish circulation, low heart rate & BP, muscle aches and stiffness incl cramps, menstrual cycles that are heavier than usual or irregular, joint pain, constipation, dry skin, coarse skin, puffy face, coarse hair, thinning hair, loss of outer 1/3 of eyebrows, depression, memory issues)": "Yes"
    },
    "blood test": {
      "TSH": 3,
      "Free T4": 0.2,
      "WBC": 4132,
      "Neutrophils %": 4132,
      "Lymphocytes %": 4312,
      "Monocytes %": 4132,
      "Eosinophils %": 4132,
      "Basophils %": 4132,
      "Glucose": 1432,
      "Sodium": 142,
      "Chloride": 12341,
      "CO2/Bicarb": 234231,
      "Electrolytes": 434,
      "Calcium": 1234,
      "Albumin": 1324,
      "SGOT/AST": 12343,
      "SGPT/ALT": 2143214,
      "TIBC": 1324321,
      "Total Iron": 4213,
      "% Saturation": 42134,
      "EBV ab VCA IgM": "Positive",
      "G6PD": 3412,
      "HbA1c": 341,
      "CEA": 1423,
      "CA 125": 4132,
      "IGF-1": 4321,
      "Reverse T3": 4321,
      "Vitamin D (25-hydroxy)": 4321,
      "EBV ab EA IgG": "Positive",
      "D-dimer": 4132,
      "VEGF - serum": 4321,
      "VEGF - plasma": 4321,
      "HsCRP": 1423,
      "CA 27.29": 4321,
      "CA15-3": 4321,
      "Homocysteine": 1342,
      "LDH/LD": 4321,
      "GGT/GGTP": 4213,
      "Total T4": 4321432,
      "Total T3": 14321,
      "SED Rate/ESR": 3241,
      "TPO antibodies": "Positive",
      "TGB antibodies": "Positive",
      "Ceruloplasmin": 4321,
      "Copper": 413243,
      "Fibrinogen": 214321,
      "Insulin": 4321,
      "Ferritin": 1432,
      "Free T3": 4132,
      "ANA": "Positive"
    },
    "gi-map": {
      "H pylori": "Present",
      "Morganella": "Present",
      "Pseudomonas": "Elevated",
      "Pseudomonas aeroginosa": "Elevated",
      "Citrobacter": "Present",
      "Desulfovibrio": "Present",
      "Citrobacter freundii": "Elevated",
      "Klebsiella": "Elevated",
      "Klebsiella pneumoniae": "Present",
      "Proteus": "Present",
      "Proteus mirabilis": "Elevated",
      "Fusobacterium": "Present",
      "Any yeasts": "Elevated",
      "Any parasites": "Present",
      "Steatocrit": "Negative",
      "Elastase-1": 4312,
      "B-glucuronidase": 1432
    },
    "hormone testing(dutch)": {
      "Estrogens": "Depressed",
      "Testosterone": "Depressed",
      "Progesterone": "Elevated",
      "4-OH pathway": "Depressed"
    },
    "stress and circadian rhythm": {
      "Cortisol": "Depressed",
      "Melatonin": "Elevated",
      "DHEA": "Elevated"
    },
    "toxins": {
      "8-OHdG": "Depressed",
      "Molds": "Depressed",
      "Pyroglutamate": "Depressed",
      "Chemicals": "Elevated",
      "Heavy Metals": "Elevated"
    },
    "genetics": {
      "Methylation": "Yes",
      "Memory & Brain Health": "Yes",
      "Inflammation": "Yes",
      "Oxidative Stress": "Yes",
      "Detoxification": "Yes",
      "Glucose & Insulin": "No",
      "Collagen & Joints": "Yes",
      "Mood & Behavior": "No",
      "Bone Health": "Yes",
      "Histamine Overload": "No",
      "Hormone Balance": "Yes",
      "Cholesterol": "No",
      "Vascular Health": "Yes",
      "Blood Pressure": "No",
      "Blood Clotting": "Yes"
    },
    "genetic snps": {
      "ACE": "Yes",
      "ACAT 1&2": "Yes",
      "ACSL 1&2": "Yes",
      "ALDH2": "Yes",
      "APOA2": "No",
      "APOE 3/4 and 4/4": "No",
      "ATM": "Yes",
      "BCM01": "Yes",
      "BHMT": "Yes",
      "COMT AA": "Yes",
      "COMT GG": "Yes",
      "CYP1A1": "Yes",
      "CYP1A2": "Yes",
      "CYP1B1": "Yes",
      "CYP2C9": "Yes",
      "CYP2D6": "Yes",
      "CYP2R1": "Yes",
      "CYP2A4": "Yes",
      "DAO": "Yes",
      "ESR 1&2": "Yes",
      "FADS1/2": "Yes",
      "FTO": "Yes",
      "GATA3": "Yes",
      "GDF5": "Yes",
      "GC": "Yes",
      "GPX1": "Yes",
      "GSTM1": "Yes",
      "GST P1": "Yes",
      "HLA": "Yes",
      "IL-1": "Yes",
      "LCT": "Yes",
      "MAOA": "Yes",
      "MDM2": "Yes",
      "MGMT": "Yes",
      "MLH1": "Yes",
      "MNSOD": "Yes",
      "MTHFD1": "Yes",
      "MTNR1B": "Yes",
      "MTHFR": "Yes",
      "NOS3": "Yes",
      "PEMT": "Yes",
      "PPARGC1A": "Yes",
      "SHBG": "Yes",
      "SIRT1": "Yes",
      "SLC22A5": "Yes",
      "TCF7L2": "Yes",
      "TP53": "Yes",
      "VDR": "Yes",
      "VKORC1*2": "Yes"
    }
  }